#   Travis-ci.org configuration file for ABRAID-MP
#   Copyright (c) 2014 University of Oxford
language:
  - java
jdk:
  - openjdk7
services:
  - postgresql
sudo: false
addons:
  postgresql: "9.3"
  apt:
    packages:
      - r-base
      - devscripts
before_cache:
  - rm -rf $HOME/.ant/cache/uk.ac.ox.zoo.seeg.abraid.*
  - rm -rf $HOME/.ant/cache/resolved-uk.ac.ox.zoo.seeg.abraid.*
  - rm -rf $HOME/.ant/resp
cache:
  # apt: true # apt caching is not yet availible on travis for open source projects
  directories:
    - $HOME/.ant
before_script:
  - git config core.fileMode false
  - chmod +x .travis.*.sh
script:
  - ./.travis.main.sh
after_success:
  - tar -zcf ${TRAVIS_TAG:-artifacts}.tar.gz artifacts
deploy:
  provider: releases
  api_key:
    secure: QkqxOMtyI8DxOonOAeh5U4eXN9OSRpUHSlY95aiCRGBUExTgi+MJqkAIKlNFgCiBZrWve0QlO75MoYcKHC6k+ORNvIdZHgqaxoM2IgQ77QoCfVoEj71rWDqh2Qo+0hhedKbaID+HoEuku/CuU07qRG6R/TBEb/EJq//dN0B6VUg=
  file: ${TRAVIS_TAG:-artifacts}.tar.gz
  skip_cleanup: true
  on:
    repo: SEEG-Oxford/ABRAID-MP
    tags: true
    all_branches: true
    jdk: openjdk7
env:
  global:
    - TERM=dumb
notifications:
  email: false
