#   Travis-ci.org configuration file for ABRAID-MP
#   Copyright (c) 2014 University of Oxford
language:
  - java
jdk:
  - openjdk7
# - oraclejdk7
services:
  - postgresql
# Note: caching is not yet enabled for travis-ci.org. When it is this should cache our dependencies.
# Note: need to be careful that the ivy-published version of common doesn't cache
#cache:
#  apt: true
#  directories:
#  - .ant/lib
#  - .ivy2/cache
before_install:
  - sudo apt-get -y -q update
install:
  - sudo apt-get -y -q install r-base devscripts
before_script:
  - chmod +x .travis.*.sh
script:
  - git status
  - ./.travis.main.sh
after_success:
  - "tar -zcf artifacts.tar.gz artifacts"
deploy:
  provider: releases
  api_key:
    secure: RJ8zk37A8Ap04ACCI8ij9ktJq5zvwC1yXaNfKlCZWqraHlBIc3AP9COFq7l7D6DVXJGNvCH0XlQpEwa8Ek9Stt7Si4Tyq+U7NPKNX6oOcTmNCH43eVq4PP4IpnPaxqQKM+bPmsMGgApZdk4oUzOBxG/+ntQbhMWq3f3jXCKTV48=
  file: artifacts.tar.gz
  skip_cleanup: true
  on:
    repo: SEEG-Oxford/ABRAID-MP
    tags: true
    all_branches: true
    jdk: openjdk7
env:
  global:
    - TERM=dumb
