<div class="leaflet-bottom leaflet-right">
    <div class="legend leaflet-bar leaflet-control">
        <div>
            This map shows the predicted probability of infections occurring at some time within a year, for every 5km x
            5km. These predictions were generated by a niche model that used disease occurrence/presence data captured
            from a range of online sources.
        </div>
    </div>
</div>
